trainer:
  max_epochs: 6
  accelerator: auto
  devices: 1
data:
  dataset_name: ETTm1
  seq_len: 96
  label_len: 48
  pred_len: 48
  variate: u
  target: OT
  frequency: t
model:
  model:
    class_path: models.Informer
    init_args:
      factor: 5
      mix_attention: TRUE
  learning_rate: 0.0001
  loss: mse
